import addCart from "./add";
const cartShop = new addCart();

describe("Functionality ADD CART tests", ()=>{
    beforeEach(()=>{
        cy.GetWeb()
        cy.LogIn()
})
it("Verify that the entire process of purchasing a product works correctly", ()=>{
    cartShop.buttonspeakers().click()
    cartShop.selectSpeaker20().click()
    cartShop.selectTitle().should('contain', 'SPEAKER')
    cartShop.selectColorGray().click()
    cartShop.buttonAdd2Cart().click()
    cartShop.clickIconCart().click()
    cartShop.verifyProduct().should('contain','BOSE SOUNDLINK BLUETOOTH SPEAKER III')
})
it("Verify that the shopping cart has the selected number of products", ()=>{
    cartShop.buttonspeakers().click()
    cartShop.selectSpeaker20().click()
    cartShop.selectTitle().should('contain', 'SPEAKER')
    cartShop.selectColorGray().click()
    cartShop.selectQuantity().type(3)
    cartShop.buttonAdd2Cart().click()
    cartShop.clickIconCart().click()
    cartShop.verifyProduct().should('contain','BOSE SOUNDLINK BLUETOOTH SPEAKER III')
    cartShop.removeFirstProduct()
})
it("Verify that the entire process of purchasing a product allows modifying the quantity in the cart", ()=>{
    cartShop.buttonspeakers().click()
    cartShop.selectSpeaker20().click()
    cartShop.selectTitle().should('contain', 'SPEAKER')
    cartShop.selectColorGray().click()
    cartShop.selectQuantity().type(3)
    cartShop.buttonAdd2Cart().click()
    cartShop.clickIconCart().click()
    cartShop.editCart().first().click()
    cartShop.decreaseProduct().click({force: true})
    cartShop.buttonAdd2Cart().click({force: true})
    cartShop.verifyProduct().should('contain','BOSE SOUNDLINK BLUETOOTH SPEAKER III')
    cartShop.removeFirstProduct()
})
it("Verify that all added products can be removed from the cart", ()=>{
    cartShop.buttonspeakers().click()
    cartShop.selectSpeaker20().click()
    cartShop.selectTitle().should('contain', 'SPEAKER')
    cartShop.selectColorGray().click()
    cartShop.selectQuantity().type(3)
    cartShop.buttonAdd2Cart().click()
    cartShop.clickIconCart().click()
    cartShop.removeProduct().first().click()
    cartShop.emptyProduct().should('contain','Your shopping cart is empty')
})
it("Verify that more than 1 product can be added to the cart", ()=>{
    cartShop.buttonspeakers().click()
    cartShop.selectSpeaker20().click()
    cartShop.selectColorGray().click()
    cartShop.buttonAdd2Cart().click()

    cartShop.buttonHome().click()
    cartShop.buttonMice().click()
    cartShop.selectMice31().click()
    cartShop.selectQuantity().type(3,{force:true})
    cartShop.buttonAdd2Cart().click({ force: true })
    cartShop.clickIconCart().click()
    cartShop.verifyProduct().should('contain','LOGITECH G502 PROTEUS CORE')
    cartShop.removeFirstProduct()
})
})
